# Predicitng Absenteeism in Work Using Logistic Regression (Machine Learning Part)

In [1]:
import pandas as pd
import numpy as np

### Load the preproccessed data

In [2]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')

In [3]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

## Create Target

In [4]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [5]:
target = np.where(data_preprocessed['Absenteeism Time in Hours']>
                data_preprocessed['Absenteeism Time in Hours'].median()  ,1,0)

In [6]:
target

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [7]:
data_preprocessed['Excessive Absent'] = target

In [8]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absent  
0                 1  
1                 0  
2                 0  
3                 1  
4                 0

## A comment on the target

In [9]:
target.sum() / target.shape[0]

0.45571428571428574

In [10]:
data_with_target = data_preprocessed.drop(['Absenteeism Time in Hours','Day of the week','Daily Work Load Average','Distance to Work'], axis = 1)

In [11]:
data_with_target is data_preprocessed

False

In [12]:
data_with_target.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0         0         0         0         1            7   
1         0         0         0         0            7   
2         0         0         0         1            7   
3         1         0         0         0            7   
4         0         0         0         1            7   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                     289   33               30          0         2     1   
1                     118   50               31          0         1     0   
2                     179   38               31          0         0     0   
3                     279   39               24          0         2     0   
4                     289   33               30          0         2     1   

   Excessive Absent  
0                 1  
1                 0  
2                 0  
3                 1  
4                 0

## Selecting the inputs for the Regression

In [13]:
data_with_target.shape

(700, 12)

In [14]:
data_with_target.iloc[:,0:14]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                       289   33               30          0         2     1   
1                       118   50               31          0         1     0   
2                       179   38               31          0         0     0   
3                       279   39               24          0         2     0   
4                       289   33               30          0         2     1   
..                      ...  ...              ...        ...       ...   ...   
695                     179   40               22          1         2     0   
696                     225   28               24          0         1     2   
697                     330   28               25          1         0     0   
698                     235   32               25          1         0     0   
699                     291   40               25          0         1     1   

     Excessive Absent  
0                   1  
1                   0  
2                   0  
3                   1  
4                   0  
..                ...  
695                 1  
696                 0  
697                 1  
698                 0  
699                 0  

[700 rows x 12 columns]

In [15]:
data_with_target.iloc[:,:-1]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  
0                       289   33               30          0         2     1  
1                       118   50               31          0         1     0  
2                       179   38               31          0         0     0  
3                       279   39               24          0         2     0  
4                       289   33               30          0         2     1  
..                      ...  ...              ...        ...       ...   ...  
695                     179   40               22          1         2     0  
696                     225   28               24          0         1     2  
697                     330   28               25          1         0     0  
698                     235   32               25          1         0     0  
699                     291   40               25          0         1     1  

[700 rows x 11 columns]

In [16]:
unscaled_inputs = data_with_target.iloc[:,:-1]

## Standardize the Data

In [17]:
##from sklearn.preprocessing import StandardScaler

##absent_scaler = StandardScaler()

In [18]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler
    

    
class CustomScaler(BaseEstimator,TransformerMixin): 
        
    def __init__(self,columns,copy=True,with_mean=True,with_std=True) :
            self.scaler = StandardScaler(copy,with_mean,with_std)
            self.columns = columns
            self.mean_ = None
            self.var_ = None
           
    def fit(self, X, y=None):
            self.scaler.fit(X[self.columns], y)
            self.mean_ = np.mean(X[self.columns])
            self.var_ = np.var(X[self.columns])
            return self
    
    def transform(self, X, y=None, copy=None):
            init_col_order = X.columns
            X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
            X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
            return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]
   

In [19]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [20]:
##columns_to_scale = ['Month Value', 'Day of the week', 'Transportation Expense', 'Distance to Work',
  ##     'Age', 'Daily Work Load Average', 'Body Mass Index',  'Children', 'Pets']
    
columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Education']

In [21]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [22]:
absent_scaler = CustomScaler(columns_to_scale)

In [23]:
absent_scaler.fit(unscaled_inputs)

CustomScaler(columns=['Month Value', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pets'],
             copy=None, with_mean=None, with_std=None)

In [24]:
scaled_inputs = absent_scaler.transform(unscaled_inputs)

In [25]:
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1     0.182726   
1           0         0         0         0     0.182726   
2           0         0         0         1     0.182726   
3           1         0         0         0     0.182726   
4           0         0         0         1     0.182726   
..        ...       ...       ...       ...          ...   
695         1         0         0         0    -0.388293   
696         1         0         0         0    -0.388293   
697         1         0         0         0    -0.388293   
698         0         0         0         1    -0.388293   
699         0         0         0         1    -0.388293   

     Transportation Expense       Age  Body Mass Index  Education  Children  \
0                  1.005844 -0.536062         0.767431          0  0.880469   
1                 -1.574681  2.130803         1.002633          0 -0.019280   
2                 -0.654143  0.248310         1.002633          0 -0.919030   
3                  0.854936  0.405184        -0.643782          0  0.880469   
4                  1.005844 -0.536062         0.767431          0  0.880469   
..                      ...       ...              ...        ...       ...   
695               -0.654143  0.562059        -1.114186          1  0.880469   
696                0.040034 -1.320435        -0.643782          0 -0.019280   
697                1.624567 -1.320435        -0.408580          1 -0.919030   
698                0.190942 -0.692937        -0.408580          1 -0.919030   
699                1.036026  0.562059        -0.408580          0 -0.019280   

         Pets  
0    0.268487  
1   -0.589690  
2   -0.589690  
3   -0.589690  
4    0.268487  
..        ...  
695 -0.589690  
696  1.126663  
697 -0.589690  
698 -0.589690  
699  0.268487  

[700 rows x 11 columns]

In [26]:
scaled_inputs.shape

(700, 11)

## Split the Data into Train and Test 

##### Import relevant Module

In [27]:
from sklearn.model_selection import train_test_split

### Split

In [28]:
train_test_split(scaled_inputs,target)

[     Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
 487         0         0         0         1     0.468236   
 176         1         0         0         0    -0.959313   
 281         0         0         0         1     0.753746   
 429         0         0         0         1    -0.388293   
 583         0         0         0         1    -1.530333   
 ..        ...       ...       ...       ...          ...   
 109         0         0         0         1     1.610276   
 338         0         0         0         1     1.324766   
 61          0         0         0         1     0.753746   
 82          1         0         0         0     1.324766   
 550         1         0         0         0     1.324766   
 
      Transportation Expense       Age  Body Mass Index  Education  Children  \
 487               -0.654143  0.248310         1.002633          0 -0.919030   
 176               -0.654143 -1.006686        -1.819793          1 -0.919030   
 281                1.0360

In [29]:
x_train,x_test,y_train,y_test = train_test_split(scaled_inputs,target, train_size = 0.8, random_state = 20)

In [30]:
print(x_train.shape,y_train.shape)

(560, 11) (560,)


In [31]:
print (x_test.shape,y_test.shape)

(140, 11) (140,)


## Logisitc Regression

### Import relevant Model

In [32]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

### Training the model

In [33]:
reg = LogisticRegression()

In [34]:
reg.fit(x_train,y_train)

C:\Users\Knowhow\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [35]:
reg.score(x_train,y_train)

0.7714285714285715

## Mannually checking the accuracy

In [36]:
model_outputs = reg.predict(x_train)
model_outputs


array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [37]:
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [38]:
np.sum(model_outputs == y_train) ## total number of correct prediction

432

In [39]:
model_outputs.shape[0]

560

In [40]:
np.sum((model_outputs == y_train)) / model_outputs.shape[0] ## Great the same result as above

0.7714285714285715

In [41]:
reg.score(x_train,y_train)

0.7714285714285715

### Extracting and interpreting the Intercept and Coefficient

In [42]:
reg.intercept_

array([-1.52555576])

In [43]:
reg.coef_

array([[ 2.68674024,  1.60939834,  1.60939834,  0.72211622,  0.15650861,
         0.61185265, -0.16874219,  0.27364466, -0.23149601,  0.34983843,
        -0.29174977]])

In [44]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [45]:
feature_name = unscaled_inputs.columns.values

In [46]:
summary_table = pd.DataFrame(columns=['Feature Name'],data = feature_name)

summary_table['Coefficient'] = np.transpose(reg.coef_)

summary_table

Feature Name  Coefficient
0                 Reason_1     2.686740
1                 Reason_2     1.609398
2                 Reason_3     1.609398
3                 Reason_4     0.722116
4              Month Value     0.156509
5   Transportation Expense     0.611853
6                      Age    -0.168742
7          Body Mass Index     0.273645
8                Education    -0.231496
9                 Children     0.349838
10                    Pets    -0.291750

In [47]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature Name  Coefficient
0                Intercept    -1.525556
1                 Reason_1     2.686740
2                 Reason_2     1.609398
3                 Reason_3     1.609398
4                 Reason_4     0.722116
5              Month Value     0.156509
6   Transportation Expense     0.611853
7                      Age    -0.168742
8          Body Mass Index     0.273645
9                Education    -0.231496
10                Children     0.349838
11                    Pets    -0.291750

In [48]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [49]:
summary_table

Feature Name  Coefficient  Odds_ratio
0                Intercept    -1.525556    0.217500
1                 Reason_1     2.686740   14.683732
2                 Reason_2     1.609398    4.999802
3                 Reason_3     1.609398    4.999802
4                 Reason_4     0.722116    2.058785
5              Month Value     0.156509    1.169421
6   Transportation Expense     0.611853    1.843844
7                      Age    -0.168742    0.844727
8          Body Mass Index     0.273645    1.314748
9                Education    -0.231496    0.793346
10                Children     0.349838    1.418838
11                    Pets    -0.291750    0.746955

In [50]:
summary_table.sort_values('Odds_ratio', ascending = False)

Feature Name  Coefficient  Odds_ratio
1                 Reason_1     2.686740   14.683732
2                 Reason_2     1.609398    4.999802
3                 Reason_3     1.609398    4.999802
4                 Reason_4     0.722116    2.058785
6   Transportation Expense     0.611853    1.843844
10                Children     0.349838    1.418838
8          Body Mass Index     0.273645    1.314748
5              Month Value     0.156509    1.169421
7                      Age    -0.168742    0.844727
9                Education    -0.231496    0.793346
11                    Pets    -0.291750    0.746955
0                Intercept    -1.525556    0.217500

In [52]:
## A feature is not really important if its coefficient is around 0 or if its odds ratio is around 1
## A weight(coefficient) of 0 means that no matter the feature value we multiply it by 0 
## for a unit change the odds increase by a multiple equal to odds ratio

## from our summary table we can see (daily work load, distance to work, and day of the week ) should be drop from our analysis

## Testing the Model

In [53]:
### Let test our trained model with the other 20% of data we kept somewhere

In [54]:
reg.score(x_test,y_test)

0.7428571428571429

In [55]:
## out test model must be lower than train model

In [56]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.71368445, 0.28631555],
       [0.58499219, 0.41500781],
       [0.44110868, 0.55889132],
       [0.78088386, 0.21911614],
       [0.08184378, 0.91815622],
       [0.33318839, 0.66681161],
       [0.30156718, 0.69843282],
       [0.10784718, 0.89215282],
       [0.787054  , 0.212946  ],
       [0.74877422, 0.25122578],
       [0.50042646, 0.49957354],
       [0.21897931, 0.78102069],
       [0.05648925, 0.94351075],
       [0.73557824, 0.26442176],
       [0.26150958, 0.73849042],
       [0.54608356, 0.45391644],
       [0.5560459 , 0.4439541 ],
       [0.54498922, 0.45501078],
       [0.39730398, 0.60269602],
       [0.04348658, 0.95651342],
       [0.70274644, 0.29725356],
       [0.78088386, 0.21911614],
       [0.42032736, 0.57967264],
       [0.42032736, 0.57967264],
       [0.21024048, 0.78975952],
       [0.74721893, 0.25278107],
       [0.50405529, 0.49594471],
       [0.8575127 , 0.1424873 ],
       [0.17032382, 0.82967618],
       [0.78088386, 0.21911614],
       [0.

In [57]:
predicted_proba.shape

(140, 2)

In [58]:
predicted_proba[:,1]

array([0.28631555, 0.41500781, 0.55889132, 0.21911614, 0.91815622,
       0.66681161, 0.69843282, 0.89215282, 0.212946  , 0.25122578,
       0.49957354, 0.78102069, 0.94351075, 0.26442176, 0.73849042,
       0.45391644, 0.4439541 , 0.45501078, 0.60269602, 0.95651342,
       0.29725356, 0.21911614, 0.57967264, 0.57967264, 0.78975952,
       0.25278107, 0.49594471, 0.1424873 , 0.82967618, 0.21911614,
       0.37237529, 0.67846692, 0.68636271, 0.52190189, 0.21911614,
       0.53676212, 0.2205312 , 0.77973704, 0.40522078, 0.61133592,
       0.21156641, 0.45322784, 0.23627634, 0.43310718, 0.82522249,
       0.62152075, 0.69454356, 0.28631555, 0.22330672, 0.20420877,
       0.57539444, 0.35567594, 0.66681161, 0.27321122, 0.83497749,
       0.43685603, 0.90263628, 0.2336417 , 0.36012492, 0.37048488,
       0.6987594 , 0.65681095, 0.29420091, 0.82446559, 0.20616454,
       0.26840777, 0.09758988, 0.2205312 , 0.77733122, 0.30061469,
       0.2205312 , 0.32256875, 0.90430257, 0.46000205, 0.60238

## Next Steps
#### 1 Save the model
#### 2 create a module
#### 3 Get new data classify it pass it through SQL and Analyze with Tableau

### Save the Model

In [59]:
import pickle

In [60]:
with open('model','wb') as file:
    pickle.dump(reg,file)


In [61]:
with open('scaler','wb')as file:
    pickle.dump(absent_scaler, file)